on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: python
          package-name: splunk_kvstore_cli
      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}
      - uses: actions/setup-python@v4
        if: ${{ steps.release.outputs.release_created }}
        with:
          python-version: "3.9"
      - run: python -m pip install build
        if: ${{ steps.release.outputs.release_created }}
      - run: python -m build
        if: ${{ steps.release.outputs.release_created }}
      - uses: pypa/gh-action-pypi-publish@v1.8.8
        if: ${{ steps.release.outputs.release_created }}
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
