on:
  push:
    branches:
      - "main"
  pull_request:
    branches: [main]

jobs:
  unit-tests:
    name: unit-tests ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install -r requirements-dev.txt
      - run: pytest tests/unit
